### ISSUE TITLE
Bug: ニックネームが「わかってくれる確率」ではなく「反応確率」になっている

### ISSUE THREAD

**Issue by Colk-tech** [2RiniaR/king-server#14]
ニックネームを、`RareReplyRate` ではなく `RareReplyRate * (「わかる」を排出する確率)` に変更する
@Colk-tech がやるかも ( C# は全く書けません )

**Comment by 2RiniaR** [comment]
景品表示法違反

**Comment by 2RiniaR** [comment]
上記、仕様です
